import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Counter from '../components/Counter';
import Form from '../components/Form';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.menu}>
          <Link href="/users">Users</Link>
          <Link href="/posts">Posts</Link>
        </div>

        <hr />
        <Counter />
        <hr />

        <Form />
      </main>
    </div>
  );
}
