import React from 'react';
import Image from 'next/image';
import Head from 'next/head';

function Users({ users }) {
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Users</h1>
      {/* <Image src="/vercel.svg" alt="" width={72} height={16} /> */}
      {users.map((item) => (
        <div key={item.id}>{item.name}</div>
      ))}

      <input type="text" />
    </>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://jsonplaceholder.typicode.com/users`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { users: data } };
}

export default Users;
